export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const RESET_CART_ITEM = "RESET_CART_ITEM";
export const SAVE_TRANSACTION_INFO = "SAVE_TRANSACTION_INFO";
